baseURL = "https://akhoshrozeh.github.io/khoshrozeh.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Khoshrozeh"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
enableGitInfo = true
disablePathToLower = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
description = ""
homeMetaContent = "Anthony Khoshrozeh Blog."
footer = "akhoshrozeh@gmail.com | [LinkedIn](https://www.linkedin.com/in/anthony-khoshrozeh/) | [Github](https://github.com/akhoshrozeh)"
# footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)." #
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = true
defaultDarkTheme = true
moveFooterToHeader = false
logoAlt = "An alternative text description of the logo"
customCss = [ "css/custom_01.css", "css/custom_02.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]

  [params.utterances]
  repo = "username/username.github.io"
  issueTerm = "title"
  theme = "github-light"

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/post/"
weight = 3

[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.nav]]
name = "Resume"
url = "/Anthony_Khoshrozeh_Resume.pdf/"
weight = 3


[[menu.nav]]
name = "About Me"
url = "/about/"
weight = 2


[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2
